tdc:
  bins  : 32
  range : [0, 32]
  label : TDC, {var} (arb. uts.)

bx:
  bins    : 3556
  range   : [0, 3556]
  label   : Bunch crossing, {var} (arb. uts.)
  log     : true

layer:
  bins  : 4
  range : [1, 5]
  label : Layer, {var}

station:
  label : Station, {var}

cell:
  bins  : 52
  range : [0, 52]
  label : Cell, {var}

channel:
  bins  : 256
  range : [0, 256]
  label : Channel, {var}

link:
  bins  : 16
  range : [0, 16]
  label : Link OBDT, {var}

sl:
  bins  : 4
  range : [1, 5]
  label : Superlayer, {var}

obdt_type:
  bins  : 2
  range : [0, 2]
  label : OBDT type, {var}

obdt_ctr:
  bins  : 15
  range : [0, 15]
  label : OBDT connector, {var}